#!/bin/sh
mapping=$(cat <<EOF
bmenu                            ===> $TERMINAL -g 100x40 -title "bmenu (floatme)" -e bmenu
morc_menu                        ===> morc_menu
pulsemixer                       ===> $TERMINAL -g 100x40 -title "pulsemixer (floatme)" -e pulsemixer
alsamixer                        ===> $TERMINAL -g 100x40 -title "alsamixer (floatme)" -e alsamixer
screenshot full screen           ===> i3-scrot -d
screenshot active window         ===> i3-scrot -w
screenshot selection             ===> i3-scrot -s
start compton                    ===> compton -b
kill compton                     ===> pkill compton
kill unresponsive window (xkill) ===> xkill
autocliker                       ===> ~/Scripts/autoclicker
select layout                    ===> ~/Scripts/dmenu_layout
restart dunst                    ===> killall dunst; notify-send "Dunst Restarted"
EOF
)
keys="$(echo "$mapping" | sed -e 's/===>.*$//g' -e 's/[ \t]*$//g')"
values="$(echo "$mapping" | sed -e 's/^.*===>//g' -e 's/^[ \t]*//g')"

result=$(echo "$keys" | dmenu -l 5 -i -p "Layout Profile")
if [[ "$result" ]]; then
  matching_line_number=$(echo "$keys" | sed -n "/$result/ =")
  eval "$(echo "$values" | sed -n "$matching_line_number p")"
fi
