#!/bin/sh
msg=$(echo "$(xbacklight -get)" | awk '{
if ($1 < 5)
  printf "🔅 (%.2f\%)", $1
else if ($1 < 50)
  print "🔅 (",int($1),"%)"
else
  print "🔆 (",int($1),"%)"
}')
DBUS_SESSION_BUSS_ADDRESS="unix:path=/run/usr/1000/bus"; notify-send "$msg" -h string:x-canonical-private-synchronous:custom_brighness_notification
