#!/bin/sh
if [ "$(pamixer --get-mute)" == "true" ]; then
  msg="🔇 ($(pamixer --get-volume)%)"
elif [ "$(pamixer --get-volume)" -eq 0 ]; then
  msg="🔇 $(pamixer --get-volume)%"
elif [ "$(pamixer --get-volume)" -lt 20 ]; then
  msg="🔈 $(pamixer --get-volume)%"
elif [ "$(pamixer --get-volume)" -lt 70 ]; then
  msg="🔉 $(pamixer --get-volume)%"
else
  msg="🔊 $(pamixer --get-volume)%"
fi
DBUS_SESSION_BUSS_ADDRESS="unix:path=/run/usr/1000/bus"; notify-send "$msg" -h string:x-canonical-private-synchronous:custom_volume_notification
