#!/bin/bash
ID=$(xdpyinfo | grep focus | cut -f4 -d " ")
PID=$(($(xprop -id "$ID" | grep -m 1 PID | cut -d " " -f 3) + 2))
if [ -e "/proc/$PID/cwd" ]; then
  if [ "$TERMINAL" == "urxvt" ]; then
    urxvt -cd "$(readlink /proc/$PID/cwd)" &
  else
    $TERMINAL
  fi
else
    $TERMINAL
fi
