#!/bin/bash
pid=$(xdotool getwindowfocus getwindowpid)
if [ -e "/tmp/cwd_data/$pid" ]; then
  cwd="$(cat "/tmp/cwd_data/$pid")"
  if [ "$TERMINAL" == "urxvt" ]; then
    urxvt -cd "$cwd"
  elif [ "$TERMINAL" == "kitty" ]; then
    kitty -d "$cwd"
  fi
else
  $TERMINAL
fi
