#!/bin/sh
xsetwacom set "Wacom Intuos S Pad pad" Button 1 "key +alt f1 -alt"
xsetwacom set "Wacom Intuos S Pad pad" Button 2 "key +alt f2 -alt"
xsetwacom set "Wacom Intuos S Pad pad" Button 3 "key +alt f3 -alt"
xsetwacom set "Wacom Intuos S Pad pad" Button 8 "key +alt f4 -alt"

xsetwacom set "Wacom Intuos S Pen stylus" Button 2 "key +alt f5 -alt"
